# List of plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'

set -g default-shell /bin/zsh

set-option -g prefix C-a     # Set Ctrl+a as the prefix
unbind C-b                   # Unbind default prefix Ctrl+b
bind C-a send-prefix         # Send Ctrl+a to applications by pressing it twice
set -g base-index 1          # start indexing windows at 1 instead of 0
set -g escape-time 0         # zero-out escape time delay
set -g extended-keys on      # pass through shift/ctrl/alt key sequences
set -g history-limit 1000000 # increase history size (from 2,000)
set -g renumber-windows on   # renumber all windows when any window is closed
bind-key x kill-pane         # skip "kill-pane 1? (y/n)" prompt
bind C-l send-keys 'C-l'     # This allows you to use Prefix + Ctrl-l to clear the screen

# Status bar
set-option -g status-position top     # Set position of status bar to the top

# Window naming: show "dirname process"
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path} #{pane_current_command}'

# macOS only
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
bind -T copy-mode-vi    C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-vi    C-WheelDownPane send-keys -X halfpage-down
bind -T copy-mode-emacs C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-emacs C-WheelDownPane send-keys -X halfpage-down

# New windows and panes inherit current path
bind c new-window -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Shift arrow to switch windows
bind -n S-Left  previous-window
bind -n S-Right next-window

# Reorder windows with Prefix + < or >
bind -r < swap-window -d -t -1
bind -r > swap-window -d -t +1

# To copy, left click and drag to highlight text in yellow,
# once you release left click yellow text will disappear and will automatically be available in clibboard
# # Use vim keybindings in copy mode
setw -g mode-keys vi
# Update default binding of `Enter` to also use copy-pipe
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "pbcopy"


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
